### ISSUE TITLE
Whatsapp web now supports Edge natively

### ISSUE THREAD

**Issue by M3d10n** [CamSoper/WhosDown#12]
There's no need to change the user-agent anymore. Should be more compatible, too, since it won't try to use Mozilla codepaths.

**Comment by CamSoper** [comment]
I noticed that too, but I left it in because it was falling back to the mobile site when I tested it on my Lumia 1520.  I didn't want to risk the app not working for users on Continuum, so I left the UA in there.

I don't suppose you have a Continuum device, do you?  I will want to test on one of those devices before I deploy with that change.

Alternatively, I guess I could only send that string when it's a mobile device...

**Comment by M3d10n** [comment]
Ah, I see. I'm using a desktop, so can't help you there. Now you've got me thinking: is it possible to test continuum on the mobile emulator?

**Comment by CamSoper** [comment]
I wish I knew.  My developer machine is a Surface Pro 3, so I didn’t install Hyper-V (so as not to disable connected standby).

**Comment by M3d10n** [comment]
I just tried it, there's no way to simulate continuum in the emulator. One idea would be to replace the Mozilla user-agent by Edge's desktop user-agent to force it to load the mobile website and use whatever Edge-specific compatibility javascript they have going.

**Comment by CamSoper** [comment]
I think what I'm going to do is exactly that - Let it use the standard UA on Windows 10, and spoof it on W10M.  Better safe than sorry, I think.  :)
